# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Admob_SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Admob_SwiftUI

  pod 'HandyJSON'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseAnalytics'
	pod 'Google-Mobile-Ads-SDK'
	pod 'FBAudienceNetwork'
  pod 'FBSDKCoreKit'
  pod 'Kingfisher'
  pod 'Firebase/RemoteConfig'



  target 'Admob_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Admob_SwiftUIUITests' do
    # Pods for testing
  end

end

post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
          end
      end
  end
